- alias: Toggle Room Light
  trigger:
    platform: mqtt
    topic: hass/light/Room
    payload: Toggle
  action:
    service: switch.toggle
    entity_id: switch.donginn_room
  id: 297fc23d6ae245ecbd504b6908d3cebf
- id: e41e7967ea2f4d63ae036306c1492d96
  alias: Lock / Unlock Router
  trigger:
  - platform: state
    entity_id: input_boolean.router
  action:
  - service_template: script.router_{{trigger.to_state.state}}
  mode: single
- id: '1605748088286'
  alias: Notify for the new release
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: Update Ready
      message: You can now update Home Assistant
  mode: single
- id: '1606088244946'
  alias: Lock Smart Router at 10pm
  description: Lock from 10pm to 8am
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: time
    after: '22:00:00'
    before: 08:00:00
  action:
  - service: mqtt.publish
    data:
      payload: 'ON'
      topic: hass/router/pi
  mode: single
- id: '1606102546391'
  alias: Unlock Smart Router
  description: Open the join access to Smart Router
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: 'OFF'
      topic: hass/router/pi
  mode: single
- id: '1606246133516'
  alias: Check the router state when HA restarts
  description: Get the existing state when home assistant restarts
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: Check
      topic: hass/router/pi
  mode: single
- id: '1606364765580'
  alias: Close garage door at 10:01
  description: Make sure that the garage door is close at 10:01pm
  trigger:
  - platform: time
    at: '22:01:00'
  condition:
  - condition: state
    entity_id: binary_sensor.garage_door_sensor_2
    state: 'on'
  action:
  - type: turn_on
    device_id: 836b6e49948ebe0f97e32736ac6fae3e
    entity_id: switch.garage_door_switch_2
    domain: switch
  mode: single
- id: '1606422593330'
  alias: Close garage door when HA restarts
  description: Make sure that the garage door is closed when home assistant restarts
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: CLOSE
      topic: sensor/garage/action1
  mode: single
- id: '1607305585230'
  alias: Garage Door Notification
  description: Send notification when garage door is open
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door_sensor_2
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_lm_x410um
    data:
      title: Garage door is open
      message: Someone opened the garage door!
  - service: notify.email_notification
    data:
      title: Garage door is open
      message: Someone opened the garage door!
  mode: single
- id: '1607847853851'
  alias: Mailbox Notification
  description: ''
  trigger:
  - platform: mqtt
    topic: hass/mailbox/state
    payload: New Mail
  condition:
  - condition: state
    entity_id: sensor.mailbox
    state: New Mail
  action:
  - service: counter.increment
    data: {}
    entity_id: counter.mbox_notify_counter
  - condition: numeric_state
    entity_id: counter.mbox_notify_counter
    below: '1'
  - service: persistent_notification.create
    data:
      notification_id: 1234
      title: You have got a mail
      message: New delivery is in the mailbox!
  - service: notify.email_notification
    data:
      title: New mail is in the mailbox
      message: Yay! New mail is in the mailbox. Check it out
  - service: notify.mobile_app_lm_x410um
    data:
      notification_id: 1234
      title: You have got a mail
      message: New delivery is in the mailbox!
  mode: single
- id: '1607878214267'
  alias: Mailbox is checked
  description: Empty the mailbox because you've got a mail
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: dismiss
    context: {}
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: hass/mailbox/state
      payload: Check
      retain: false
  - service: counter.reset
    data: {}
    entity_id: counter.mbox_notify_counter
  mode: single
