- platform: mqtt
  name: "mailbox"
  state_topic: "hass/mailbox/state"
  
- platform: template
  sensors:
    mailbox_template:
      friendly_name: "Mail Box"
      value_template: >-
        {% if is_state('sensor.mailbox', 'Empty') %}
          Empty
        {% else %}
          New Mail
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.mailbox', 'Empty') %}
          mdi:mailbox
        {% else %}
          mdi:mailbox-up
        {% endif %}
