title: DongInn's Home Automation
resources:
  - url: /local/button-card.js
    type: module

button_card_templates:
  header:
    styles:
      card:
        - padding: 5px 15px
        - background-color: var(--paper-item-icon-active-color)
      name:
        - text-transform: uppercase
        - color: var(--primary-background-color)
        - justify-self: start
        - font-weight: bold
      label:
        - text-transform: uppercase
        - color: var(--primary-background-color)
        - justify-self: start
        - font-weight: bold
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: binary_sensor.office_ding
      - entity: binary_sensor.office_motion
      - entity: person.donginn_kim
      - entity: sensor.us_coronavirus_confirmed
      - entity: sensor.us_coronavirus_current
      - entity: sensor.us_coronavirus_recovered
      - entity: sensor.us_coronavirus_deaths
      - entity: sensor.office_battery
      - entity: sensor.office_volume
      - entity: sensor.office_last_activity
      - entity: sensor.office_last_ding
      - entity: sensor.office_last_motion
      - entity: sun.sun
    cards:
      - type: picture-entity
        entity: camera.front_door
      - type: entities
        entities:
          - binary_sensor.front_door_ding
          - binary_sensor.front_door_motion
          - sensor.front_door_last_activity
          - sensor.front_door_last_ding
          - sensor.front_door_last_motion
          - sensor.front_door_volume
      - type: entities
        entities:
          - sensor.hp_officejet_pro_8600_black_ink
          - sensor.hp_officejet_pro_8600_cyan_ink
          - sensor.hp_officejet_pro_8600_magenta_ink
          - sensor.hp_officejet_pro_8600_yellow_ink
          - sensor.hp_officejet_pro_8600
        title: Family room
      - type: thermostat
        entity: climate.nest_thermostat
      - type: entities
        entities:
          - switch.donginn_room
          - sensor.mfc_465cn_status
          - sensor.mfc_465cn_page_counter
          - sensor.mfc_465cn_black_ink_remaining
          - sensor.mfc_465cn_cyan_ink_remaining
          - sensor.mfc_465cn_magenta_ink_remaining
          - sensor.mfc_465cn_yellow_ink_remaining
          - sensor.mfc_465cn_uptime
          - sensor.r7000_gateway_b_sent
          - sensor.r7000_gateway_packets_received
          - sensor.r7000_gateway_packets_sent
          - sensor.r7000_gateway_kib_s_received
          - sensor.r7000_gateway_kib_s_sent
          - sensor.r7000_gateway_packets_s_received
          - sensor.r7000_gateway_packets_s_sent
          - sensor.r7000_gateway_b_received
        title: Study room
      - type: entities
        entities:
          - sensor.nest_thermostat_humidity
          - sensor.nest_thermostat_temperature
        title: Hallway
      - type: picture-entity
        entity: camera.office_camera_test
      - type: weather-forecast
        entity: weather.home
        show_forecast: false
      - type: entities
        entities:
          - type: 'custom:button-card'
            entity: switch.safe_router
            show_name: false
            size: 25%
            state:
              - value: 'off'
                color: red
                icon: mdi:lock-open
              - value: 'on'
                color: green
                icon: mdi:lock
          - card:
            entity: switch.safe_router
            name: 'Unlock / Lock'
          - type: weblink
            name: Manage Attached Devices
            url: 'http://pipact1.local:8080/'
            icon: 'mdi:lan'
        title: Safe Router
        show_header_toggle: false
